name: "下班"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Run sign
        env:
          MOGUDING_DEVICE: android
          MOGUDING_PHONE: 16710247492
          MOGUDING_PASSWORD: Zph123456
          MOGUDING_PROVINCE: 云南省
          MOGUDING_CITY: 昆明市
          MOGUDING_ADDRESS: 官渡区太和街道拓东路15
          MOGUDING_LONGITUDE: 102.71871
          MOGUDING_LATITUDE: 25.0332
          MOGUDING_TYPE: "END"
          MOGUDING_DESCRIPTION: ${{ secrets.DESCRIPTION }}
          MOGUDING_SCT_KEY: ${{ secrets.SENDKEY }}
        run: php artisan moguding
